apiVersion: apps/v1
kind: Deployment
metadata:
  name: deliver
  labels:
    app: deliver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deliver
  template:
    metadata:
      labels:
        app: deliver
    spec:
      containers:
        - name: deliver
          image: username/deliver:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5